/******************************************************************************
*
* Module: Port
*
* File Name: Port_PBCfg.C
*
* Author: Mohamed Hossam
******************************************************************************/

#include "Port.h"



const Port_ConfigType Port_Configuration={
  /* PORT A */
  PORTA,PIN0,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTA,PIN1,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTA,PIN2,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTA,PIN3,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTA,PIN4,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTA,PIN5,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTA,PIN6,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTA,PIN7,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,



  /* PORT B */
  PORTB,PIN0,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTB,PIN1,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTB,PIN2,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTB,PIN3,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTB,PIN4,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTB,PIN5,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTB,PIN6,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTB,PIN7,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,



  /* WARINGIN : COMMENTING SOME INITIALIZATION DUE TO FACING "TOO MANY INITIALIZER ERROR" */


  /* PORT C
  PORTC,PIN0,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTC,PIN1,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTC,PIN2,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTC,PIN3,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTC,PIN4,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTC,PIN5,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTC,PIN6,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTC,PIN7,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  */

  /* PORT D */
  PORTD,PIN0,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTD,PIN1,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTD,PIN2,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTD,PIN3,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTD,PIN4,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTD,PIN5,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTD,PIN6,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTD,PIN7,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,

  /* PORT E */
  PORTE,PIN0,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTE,PIN1,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTE,PIN2,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTE,PIN3,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTE,PIN4,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTE,PIN5,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,

  /* PORT F */
  PORTF,PIN0,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTF,PIN1,OUTPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON, // LED PIN
  PORTF,PIN2,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTF,PIN3,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
  PORTF,PIN4,INPUT,OFF,STD_LOW,PortConfig_Mode_DIO,MODE_CHANGE_ON,DIRECTION_CHANGE_ON,
};
